name:                 memoization
version:              0.1.0.0
visibility:           public
id:                   memoization-0.1.0.0-GTYX0Qbn4AuGMZkAxjEY3V
key:                  memoization-0.1.0.0-GTYX0Qbn4AuGMZkAxjEY3V
license:              BSD-3-Clause
copyright:            2025 Noric Couderc
maintainer:           noric.couderc@cs.lth.se
author:               Noric Couderc
homepage:             https://github.com/githubuser/memoization#readme
description:
    Please see the README on GitHub at <https://github.com/githubuser/memoization#readme>

abi:                  682500f89a226816b96e8d0cac930242
exposed:              True
exposed-modules:      Memoization MonadicMemoization StringAlignment
hidden-modules:       Paths_memoization
import-dirs:
    C:\Users\tonny\Downloads\A2N-Memoization\assignment\.stack-work\install\b9950901\lib\x86_64-windows-ghc-9.4.8\memoization-0.1.0.0-GTYX0Qbn4AuGMZkAxjEY3V

library-dirs:
    C:\Users\tonny\Downloads\A2N-Memoization\assignment\.stack-work\install\b9950901\lib\x86_64-windows-ghc-9.4.8\memoization-0.1.0.0-GTYX0Qbn4AuGMZkAxjEY3V
    C:\Users\tonny\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\tonny\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

library-dirs-static:
    C:\Users\tonny\Downloads\A2N-Memoization\assignment\.stack-work\install\b9950901\lib\x86_64-windows-ghc-9.4.8\memoization-0.1.0.0-GTYX0Qbn4AuGMZkAxjEY3V
    C:\Users\tonny\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\tonny\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

dynamic-library-dirs:
    C:\Users\tonny\Downloads\A2N-Memoization\assignment\.stack-work\install\b9950901\lib\x86_64-windows-ghc-9.4.8
    C:\Users\tonny\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\tonny\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

data-dir:
    C:\Users\tonny\Downloads\A2N-Memoization\assignment\.stack-work\install\b9950901\share\x86_64-windows-ghc-9.4.8\memoization-0.1.0.0

hs-libraries:         HSmemoization-0.1.0.0-GTYX0Qbn4AuGMZkAxjEY3V
include-dirs:
    C:\Users\tonny\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\include

depends:
    base-4.17.2.1 containers-0.6.7 mtl-2.2.2
    random-1.2.1.1-5A411GLqDA5B9LXzgGkW7g

haddock-interfaces:
    C:\Users\tonny\Downloads\A2N-Memoization\assignment\.stack-work\install\b9950901\doc\memoization-0.1.0.0\memoization.haddock

haddock-html:
    C:\Users\tonny\Downloads\A2N-Memoization\assignment\.stack-work\install\b9950901\doc\memoization-0.1.0.0
